# Generated by Django 5.2.13 on 2026-05-06 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="amount_paid",
            new_name="advance_paid",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="color_code",
            new_name="primary_color",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="amount_pending",
            new_name="remaining_amount",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="project",
            name="secondary_color",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="staff_members",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "staff"},
                related_name="staff_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "manager"},
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
