# Generated by Django 5.2.14 on 2026-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_amount_paid_project_advance_paid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("e_commerce", "E-Commerce"),
                            ("custom_development", "Custom Development"),
                            ("app_development", "App Development"),
                        ],
                        max_length=40,
                    ),
                ),
                ("context", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("heated", "Heated"),
                            ("converted", "Converted"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("meta_ads", "Meta Ads"),
                            ("google_ads", "Google Ads"),
                            ("manual", "Manual"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=30,
                    ),
                ),
                (
                    "external_lead_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Lead ID from Meta, Google, or another external platform.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "campaign_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("adset_name", models.CharField(blank=True, max_length=255, null=True)),
                ("adset_id", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_name", models.CharField(blank=True, max_length=255, null=True)),
                ("ad_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        help_text="Original payload received from lead forms or ad platforms.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
                "ordering": ("-created_at",),
            },
        ),
    ]
