# Generated by Django 5.2.14 on 2026-05-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_lead_newslettersubscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="service",
            field=models.CharField(
                choices=[
                    ("e_commerce", "E-Commerce"),
                    ("ai_automation", "AI-Powered Automation"),
                    ("custom_crm", "Custom CRM Development"),
                    ("custom_development", "Custom Development"),
                    ("app_development", "App Development"),
                ],
                max_length=40,
            ),
        ),
    ]
